# Generated by Django 4.2.2 on 2023-07-05 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payslip_app', '0003_employeesdetails_delete_earnings_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employeesdetails',
            old_name='salary_arrears',
            new_name='travel_allowance',
        ),
    ]
